routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::get('/fullpost', function () {
    return view('fullPost');
});

Route::get('/', 'frontendController@index');
Route::get('/post/{id}', 'frontendController@show')->name('postdetail');
Route::post('/comment/{id}', 'CommentController@store')->name('comment.store');



Route::prefix('users')->name('user.')->group(function () {
	Route::get('/', 'UsersController@index')->name('index');
    Route::get('/add', 'UsersController@create')->name('create');
    Route::post('/', 'UsersController@store')->name('store');
    Route::get('/edit/{id}', 'UsersController@edit')->name('edit');
    Route::put('/{id}', 'UsersController@update')->name('update');
    Route::get('/view/{id}', 'UsersController@show')->name('view');
    Route::delete('/delete/{id}','UsersController@destroy')->name('delete');
});

Route::prefix('posts')->name('posts.')->group(function () {
    Route::get('/', 'PostController@index')->name('index');
    Route::get('/addpost', 'PostController@create')->name('create');
    Route::post('/', 'PostController@store')->name('store');
    Route::get('/edit/{id}', 'PostController@edit')->name('edit');
    Route::put('/{id}', 'PostController@update')->name('update');
    Route::get('/view/{id}', 'PostController@show')->name('view');
    Route::delete('/delete/{id}','PostController@destroy')->name('delete');
    Route::get('/image/{id}', 'ImageController@index')->name('image');
    Route::post('/image/{id}', 'ImageController@store')->name('image.save');

});

Route::get('/login', 'LoginController@showLoginForm')->name('login');
Route::post('/login', 'LoginController@login');
Route::post('/logout', 'LoginController@logout')->name('logout');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', 'DashboardController@index');
});

Route::get('/password/reset', 'ForgotPasswordController@showForm')->name('password.request');
Route::post('password/email', 'ForgotPasswordController@sendEmail')->name('password.email');
Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'ResetPasswordController@resetPassword')->name('password.update');

/*Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');*/

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Kyslik\ColumnSortable\Sortable;
use App\Notifications\CustomResetPasswordNotification;

class User extends Authenticatable
{
    use Sortable;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public $sortable = [
        'id', 'name', 'email',
    ];
    
    /**
     * Send the password reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new CustomResetPasswordNotification($token));
    }

    public function posts()
    {
        return $this->hasMany('App\Post');
    }

    public function comments(){
        return $this->hasMany('App\Comment');
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Image;
use DB;
use App\Registration;

class UserController extends Controller
{
    
    public function index(){
	    $users = DB::select('select * from registrations');
	    return view('userlist',['users'=>$users]);
    }

    public function store(Request $request)
    {
    	/*$this->validate($request,[
			'name'=>'required|min:5',
			'email'=>'required|email',
			'password'=>'required',
      	]);*/
      	$name = $request->name;
      	$email = $request->email;
      	$password = $request->password;
        if ($request->hasFile('image')) {
            $image = $request->image;
            //image name with Extension
            $filenamewithextension = $image->getClientOriginalName();
            //image name without Extension
            $filename = pathinfo($filenamewithextension, PATHINFO_FILENAME);
            //get file extension
            $extension = $image->getClientOriginalExtension();
            //filename to store
            $filenametostore = $filename.'_'.uniqid().'.'.$extension;
            
            Storage::put('public/images/'. $filenametostore, fopen($image, 'r+'));
            Storage::put('public/images/thumbnail/'. $filenametostore, fopen($image, 'r+'));
            $thumbnailpath = public_path('storage/images/thumbnail/'.$filenametostore);
            $img = Image::make($thumbnailpath)->resize(100, 100)->save($thumbnailpath);
        }
        $data=array('name'=>$name,"email"=>$email,"password"=>$password,"image"=>$filenametostore);
	    DB::table('registrations')->insert($data);
	    //return redirect()->back()->with('message', 'User Registered successfully');
        //return redirect()->route('view-records');
        return redirect()->action('UserController@index')->with('message', 'User Registered successfully');
    }

    public function show($id){
        $user = Registration::find($id);
    	return view('edit',[
            'user'=>$user
        ]);
    }

    public function update(Request $request){
    	$id = $request->hidden_id;
    	$name = $request->name;
    	$email = $request->email;
    	$password = $request->password;
        $image = $request->image;
        if ($image=="") {
            $users = DB::select('select image from registrations where id = ?',[$id]);
            $image = $users[0]->image;
            DB::update('update registrations set name = ?, email = ?, password = ?, image = ? where id = ?',[$name,$email,$password,$image,$id]);
            return redirect()->action('UserController@index')->with('message', 'User Updated successfully');  
        }else{
            if ($request->hasFile('image')) {
                $image = $request->image;
                //image name with Extension
                $filenamewithextension = $image->getClientOriginalName();
                //image name without Extension
                $filename = pathinfo($filenamewithextension, PATHINFO_FILENAME);
                //get file extension
                $extension = $image->getClientOriginalExtension();
                //filename to store
                $filenametostore = $filename.'_'.uniqid().'.'.$extension;
                Storage::put('public/images/'. $filenametostore, fopen($image, 'r+'));
                Storage::put('public/images/thumbnail/'. $filenametostore, fopen($image, 'r+'));
                $thumbnailpath = public_path('storage/images/thumbnail/'.$filenametostore);
                $img = Image::make($thumbnailpath)->resize(100, 100)->save($thumbnailpath);
                DB::update('update registrations set name = ?, email = ?, password = ?, image = ? where id = ?',[$name,$email,$password,$filenametostore,$id]);
                return redirect()->action('UserController@index')->with('message', 'User Updated successfully');
            }
        }
    }
    public function delete($id){
        $users = DB::select('select image from registrations where id = ?',[$id]);
        $image = $users[0]->image;
        if(Storage::exists('public/images/'.$image) && Storage::exists('public/images/thumbnail/'.$image)) {
            if(Storage::delete('public/images/'.$image) && Storage::delete('public/images/thumbnail/'.$image)){
                DB::delete('delete from registrations where id = ?',[$id]);
                return redirect()->back()->with('message', 'User Deleted successfully');
            }else{
                dd('no');
            }
        } else {
            dd('no');
        }
    	
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\UserStoreRequest;
use App\Repositories\UserRepository;


class UsersController extends Controller
{
    protected $usersRepository;

    public function __construct(UserRepository $users)
    {
        $this->usersRepository = $users;
    }

    public function index(Request $request)
    {
        $users = $this->usersRepository->paginate($request);
        return view('users.user',[
            'users'=>$users
        ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.createuser');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserStoreRequest $request)
    {
        $this->usersRepository->store($request);
        return redirect()->route('user.index')->with('message', 'User Registered successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user_detail = $this->usersRepository->show($id);
        return view('users.userdetail',[
            'user'=>$user_detail
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user_editing = $this->usersRepository->edit($id);
        return view('users.edit',[
            'user'=>$user_editing
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->usersRepository->update($id, $request);
        return redirect()->route('user.index')->with('message', 'User Updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->usersRepository->delete($id);
        return redirect()->route('user.index')->with('message', 'User deleted successfully');
    }
}

resources/views/users/createuser.blade.php
@extends('../layout.master')
@section('title', 'Registration Form')
@section('content')
	<section class="header_section">
	    <div class="container">
	        <div class="row">
	            <div class="col-xl-12">
	                <div class="header">
	                    <h4>
	                        Registration Form
	                    </h4>
	                    <a href="{{ route('user.index')}}" class="btn btn-success">Back</a>
	                </div>
	            </div>
	        </div>
	    </div>
	</section>
	<section class="form_section">
		<div class="container">
			<div class="row">
				<div class="col-xl-12">
					<div class="form_area">
					    <form action="{{ route('user.store')}}" method="POST" enctype="multipart/form-data">
					        {{ csrf_field() }}
					        <div class="row">
					            <div class="form-group">
					                <label>Name:</label>
					                <input type="text" class="form-control" name="name">
					                @error('name')
					                    <div class="text-danger">{{ $message }}</div>
					                @enderror
					            </div>
					        </div>
					        <div class="row">
					            <div class="form-group">
					                <label>Email:</label>
					                <input type="email" class="form-control" name="email">
					                @error('email')
					                    <div class="text-danger">{{ $message }}</div>
					                @enderror
					            </div>
					        </div>
					        <div class="row">
					            <div class="form-group">
					                <label>password:</label>
					                <input type="password" class="form-control" name="password">
					                @error('password')
					                    <div class="text-danger">{{ $message }}</div>
					                @enderror
					            </div>
					        </div>
					        <div class="row">
					            <div class="form-group">
					                <label>Status:</label>
					                <select class="form-control" name="status">
					                	<option>Select the status</option>
					                	<option value="1">Active</option>
					                	<option value="0">Deactive</option>
					                </select>
					                @error('status')
					                    <div class="text-danger">{{ $message }}</div>
					                @enderror
					            </div>
					        </div>
					        <div class="row">
					            <div class="form-group">
					                <label>Image:</label>
					                <input type="file" class="form-control" name="image">
					                @error('image')
					                    <div class="text-danger">{{ $message }}</div>
					                @enderror
					            </div>
					        </div>
					        <div class="row">
					            <div class="form-group">
					                <input type="submit" class="btn btn-info" name="submit" value="Add">
					            </div>
					        </div>
					    </form>
					</div>
				</div>
			</div>
		</div>
	</section>
@endsection

resources/views/users/edit.blade.php
@extends('../layout.master')
@section('title', 'User Update')
@section('content')
	<section class="header_section">
	    <div class="container">
	        <div class="row">
	            <div class="col-xl-12">
	                <div class="header">
	                    <h4>
	                        Update User
	                    </h4>
	                </div>
	            </div>
	        </div>
	    </div>
	</section>
	<section class="form_section">
		<div class="container">
			<div class="row">
				<div class="col-xl-12">
					<div class="form_area">
					    <form action="{{ route('user.update', ['id' => $user->id]) }}" method="POST" enctype="multipart/form-data">
					    	{{method_field('PUT')}}
					        {{ csrf_field() }}
					        <div class="row">
					            <div class="form-group">
					                <label>Name:</label>
					                <input type="text" class="form-control" name="name" value="{{$user->name}}">
					            </div>
					        </div>
					        <div class="row">
					            <div class="form-group">
					                <label>Email:</label>
					                <input type="email" class="form-control" name="email" value="{{$user->email}}">
					            </div>
					        </div>
					        <div class="row">
					            <div class="form-group">
					                <label>Status:</label>
					                <select class="form-control" name="status">
					                	@php
					                		$value = $user->status;
					                	@endphp
					                	<option value="1"
					                		@php
					                			if($value == 1){
					                				echo 'selected';
					                			}
											@endphp
					                	>Active</option>
					                	<option value="0"
            		                		@php 
            		                			if($value == 0){
            		                				echo 'selected';
            		                			}
            								@endphp
					                	>Deactive</option>
					                </select>
					            </div>
					        </div>
					        <div class="row">
					            <div class="form-group">
					                <label>Image:</label>
					                <input type="file" class="form-control" name="image">
					                <img src="{{ asset('storage/images/').'/'.$user->image}}" alt="..." height="50" width="50" />
					            </div>
					        </div>
					        <div class="row">
					            <div class="form-group">
					                <input type="submit" class="btn btn-info" name="submit" value="Update">
					            </div>
					        </div>
					    </form>
					</div>
				</div>
			</div>
		</div>
	</section>
@endsection

resources/views/users/user.blade.php
@extends('../layout.master')
@section('title', 'Laravel-Crud')
@section('content')
	<section class="main_section">
		@if(session()->has('message'))
		    <div class="alert alert-success">
		        {{ session()->get('message') }}
		    </div>
		@endif 
    	<div class="col-xl-12">
    		<div class="top_bar">
				<div class="left">
					<form action="{{ route('user.index') }}" method="GET" role="search">
						<input type="text" class="form-control" placeholder="Enter Name" name="name" value="{{ Request::input('name') }}">
						<input type="text" class="form-control" placeholder="Enter Email" name="email" value="{{ Request::input('email') }}">
						<div class="input-group">
							&nbsp;
							<input type="submit" value="Search" class="btn btn-info">
							&nbsp;
							<a href="{{ route('user.index') }}" class="btn btn-success">Reset</a>
						</div>
					</form>
				</div>
				<div class="right">
					<a href="{{ route('user.create') }}" class="btn btn-info">Add User</a>
					<a href="{{ route('user.index') }}" class="btn btn-success">Back</a>
				</div>
    		</div>
			<div class="table-responsive">
				<table class="table table-hover">
					<thead>
						<tr>
							<th>@sortablelink('id', 'ID')</th>
							<th>@sortablelink('name', 'Name')</th>
							<th>@sortablelink('email', 'Email')</th>
							<th>Image</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
						@if(count($users) > 0)
							@foreach ($users as $user)
								<tr>
									<td>{{ $user->id }}</td>
									<td>{{ $user->name }}</td>
									<td>{{ $user->email }}</td>
									<td>
										<img src="{{ asset('storage/images').'/' .$user->image }}" alt="..." height="30" width="30" />
									</td>
									<td>
										<a href="{{ route('user.edit', ['id' => $user->id]) }}" class="btn btn-info">
											<i class="fa fa-pencil"></i>
										</a>
										<a href="{{ route('user.view', ['id' => $user->id]) }}" class="btn btn-primary">
											<i class="fa fa-eye"></i>
										</a>
										<form method="POST" action="{{ route('user.delete', ['id' => $user->id]) }}">
										    {{ csrf_field() }}
										    {{ method_field('DELETE') }}
										    <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
										</form>
									</td>
								</tr>
							@endforeach
						@else
							<tr>
								<td colspan="5">{{ 'No Record Found ! Try Again!!' }}</td>
							</tr>
						@endif
					</tbody>
				</table> 
				{!! $users->appends(request()->except('page'))->render() !!}
			</div>
    	</div>
	</section>
@endsection

resources/views/users/userdetail.blade.php
@extends('../layout.master')
@section('title', 'Laravel-Crud')
@section('content')
	<section class="main_section">
		<div class="container">
		    <div class="row">
		    	<div class="col-xl-12">
		    		<div class="top_bar">
						<div class="left">
						</div>
						<div class="right">
							<a href="{{ route('user.index') }}" class="btn btn-success">Back</a>
						</div>
		    		</div>
					<div class="table-responsive">
						<table class="table table-hover">
							<thead>
								<tr>
									<th>Sr no.</th>
									<th>Name</th>
									<th>Email</th>
									<th>Image</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>{{$user->id}}</td>
									<td>{{$user->name}}</td>
									<td>{{$user->email}}</td>
									<td>
										<img src="{{ asset('storage/images').'/' .$user->image }}" alt="..." height="50" width="50" />
									</td>
								</tr>
							</tbody>
						</table>  
					</div>
		    	</div>
			</div>
		</div>
	</section>
@endsection