routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::get('/fullpost', function () {
    return view('fullPost');
});

Route::get('/', 'frontendController@index');
Route::get('/post/{id}', 'frontendController@show')->name('postdetail');
Route::post('/comment/{id}', 'CommentController@store')->name('comment.store');



Route::prefix('users')->name('user.')->group(function () {
	Route::get('/', 'UsersController@index')->name('index');
    Route::get('/add', 'UsersController@create')->name('create');
    Route::post('/', 'UsersController@store')->name('store');
    Route::get('/edit/{id}', 'UsersController@edit')->name('edit');
    Route::put('/{id}', 'UsersController@update')->name('update');
    Route::get('/view/{id}', 'UsersController@show')->name('view');
    Route::delete('/delete/{id}','UsersController@destroy')->name('delete');
});

Route::prefix('posts')->name('posts.')->group(function () {
    Route::get('/', 'PostController@index')->name('index');
    Route::get('/addpost', 'PostController@create')->name('create');
    Route::post('/', 'PostController@store')->name('store');
    Route::get('/edit/{id}', 'PostController@edit')->name('edit');
    Route::put('/{id}', 'PostController@update')->name('update');
    Route::get('/view/{id}', 'PostController@show')->name('view');
    Route::delete('/delete/{id}','PostController@destroy')->name('delete');
    Route::get('/image/{id}', 'ImageController@index')->name('image');
    Route::post('/image/{id}', 'ImageController@store')->name('image.save');

});

Route::get('/login', 'LoginController@showLoginForm')->name('login');
Route::post('/login', 'LoginController@login');
Route::post('/logout', 'LoginController@logout')->name('logout');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', 'DashboardController@index');
});

Route::get('/password/reset', 'ForgotPasswordController@showForm')->name('password.request');
Route::post('password/email', 'ForgotPasswordController@sendEmail')->name('password.email');
Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'ResetPasswordController@resetPassword')->name('password.update');

/*Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');*/

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
	use SoftDeletes;
	
    protected $fillable = [
		'user_id','post_name', 'short_description','description','status'
	];

	public function users()
	{
		return $this->belongsTo('App\User', 'user_id');
	}

	public function images(){
		return $this->hasmany('App\Image');
	}

	public function comments(){
		return $this->hasmany('App\Comment');
	}

	public function delete()
    {
        // delete all associated photos
        $this->images()->delete();

        // delete the user
        return parent::delete();
    }

    
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\PostStoreRequest;
use App\Repositories\PostRepository;


class PostController extends Controller
{
	protected $postRepository;

	public function __construct(PostRepository $posts)
	{
	    $this->postRepository = $posts;
	}

    public function index(){
    	$posts = $this->postRepository->paginate();
    	return view('posts.postList',[
    		'posts'=>$posts
    	]);
    }

    public function create(){
    	return view('posts.createPost');
    }

    public function store(PostStoreRequest $request){
    	$this->postRepository->store($request);
    	return redirect()->route('posts.index')->with('message', 'Post created successfully');
	}

	public function show($id){
		$post = $this->postRepository->show($id);
		return view('posts.postDetail', [
			'post'=>$post
		]);
	}

	public function edit($id){
		$post = $this->postRepository->edit($id);
		return view('posts.editPost', [
			'post'=>$post
		]); 
	}

	public function update(Request $request, $id){
		$this->postRepository->update($id, $request);
		return redirect()->route('posts.index')->with('message', 'Post Updated successfully');
	}

	public function destroy($id){
		$this->postRepository->delete($id);
		return redirect()->route('posts.index')->with('message', 'Post Deleted successfully');
	}
}

resources/views/posts/createPost.blade.php
@extends('../layout.master')
@section('title', 'Create Post')
@section('content')

	<section class="main_section">
		@if(session()->has('message'))
		    <div class="alert alert-success">
		        {{ session()->get('message') }}
		    </div>
		@endif 
    	<div class="col-xl-12">
    		<div class="top_bar">
				<div class="left">
					<h2 class="text-info">
						Create Post
					</h2>
				</div>
				<div class="right">
					<a href="{{ route('posts.index') }}" class="btn btn-success">Back</a>
				</div>
    		</div>
    	</div>
    	<section class="form_section">
    		<div class="container">
    			<div class="row">
    				<div class="col-xl-12">
    					<div class="form_area">
    					    <form action="{{ route('posts.store') }}" method="POST" enctype="multipart/form-data">
    					        {{ csrf_field() }}
    					        <div class="row">
    					        	<div class="col-xl-6">
	    					            <div class="form-group">
	    					                <label>Post Title:</label>
	    					                <input type="text" class="form-control" name="name">
	    					                @error('name')
	    					                    <div class="text-danger">{{ $message }}</div>
	    					                @enderror
	    					            </div>
    					        	</div>
    					        </div>
    					        <div class="row">
    					        	<div class="col-xl-6">
	    					            <div class="form-group">
	    					                <label>Short Description:</label>
	    					                <input type="text" class="form-control" name="short_description">
	    					                @error('short_description')
	    					                    <div class="text-danger">{{ $message }}</div>
	    					                @enderror
	    					            </div>
    					        	</div>
    					        </div>
    					        <div class="row">
    					        	<div class="col-xl-6">
	    					            <div class="form-group">
	    					                <label>Description:</label>
	    					                <textarea class="form-control" rows="4" col="5" name="description"></textarea>
	    					                @error('description')
	    					                    <div class="text-danger">{{ $message }}</div>
	    					                @enderror
	    					            </div>
    					        	</div>
    					        </div>
    					        <div class="row">
    					        	<div class="col-xl-6">
	    					            <div class="form-group">
	    					                <label>Status:</label>
	    					                <select class="form-control" name="status">
	    					                	<option>Select the status</option>
	    					                	<option value="1">Active</option>
	    					                	<option value="0">Deactive</option>
	    					                </select>
	    					                @error('status')
	    					                    <div class="text-danger">{{ $message }}</div>
	    					                @enderror
	    					            </div>
    					        	</div>
    					        </div>
    					        <div class="row">
    					        	<div class="col-xl-6">
	    					            <div class="form-group">
	    					                <input type="submit" class="btn btn-info" name="submit" value="Add">
	    					            </div>
	    					        </div>
    					        </div>
    					    </form>
    					</div>
    				</div>
    			</div>
    		</div>
    	</section>
	</section>

@endsection

resources/views/posts/editPost.blade.php
@extends('../layout.master')
@section('title', 'Edit Post')
@section('content')

	<section class="main_section">
    	<div class="col-xl-12">
    		<div class="top_bar">
				<div class="left">
					<h2 class="text-info">
						Create Post
					</h2>
				</div>
				<div class="right">
					<a href="{{ route('posts.index') }}" class="btn btn-success">Back</a>
				</div>
    		</div>
    	</div>
    	<section class="form_section">
    		<div class="container">
    			<div class="row">
    				<div class="col-xl-12">
    					<div class="form_area">
    					    <form action="{{ route('posts.update', ['id' => $post->id])}}" method="POST" enctype="multipart/form-data">
    					    	{{method_field('PUT')}}
    					        {{ csrf_field() }}
    					        <div class="row">
    					        	<div class="col-xl-6">
	    					            <div class="form-group">
	    					                <label>Post Title:</label>
	    					                <input type="text" class="form-control" name="name" value="{{ $post->post_name }}">
	    					                @error('name')
	    					                    <div class="text-danger">{{ $message }}</div>
	    					                @enderror
	    					            </div>
    					        	</div>
    					        </div>
    					        <div class="row">
    					        	<div class="col-xl-6">
	    					            <div class="form-group">
	    					                <label>Short Description:</label>
	    					                <input type="text" class="form-control" name="short_description" value="{{ $post->short_description }}">
	    					                @error('short_description')
	    					                    <div class="text-danger">{{ $message }}</div>
	    					                @enderror
	    					            </div>
    					        	</div>
    					        </div>
    					        <div class="row">
    					        	<div class="col-xl-6">
	    					            <div class="form-group">
	    					                <label>Description:</label>
	    					                <textarea class="form-control" rows="4" col="5" name="description">
	    					                {{$post->description}}
	    					                </textarea>
	    					                @error('description')
	    					                    <div class="text-danger">{{ $message }}</div>
	    					                @enderror
	    					            </div>
    					        	</div>
    					        </div>
    					        <div class="row">
    					        	<div class="col-xl-6">
	    					            <div class="form-group">
	    					                <label>Status:</label>
	    					                <select class="form-control" name="status">
	    					                	@php
    						                		$value = $post->status;
    						                	@endphp
    						                	<option value="1"
    						                		@php
    						                			if($value == 1){
    						                				echo 'selected';
    						                			}
    												@endphp
    						                	>Active</option>
    						                	<option value="0"
    	            		                		@php 
    	            		                			if($value == 0){
    	            		                				echo 'selected';
    	            		                			}
    	            								@endphp
    						                	>Deactive</option>
	    					                </select>
	    					                @error('status')
	    					                    <div class="text-danger">{{ $message }}</div>
	    					                @enderror
	    					            </div>
    					        	</div>
    					        </div>
    					        <div class="row">
    					        	<div class="col-xl-6">
	    					            <div class="form-group">
	    					                <input type="submit" class="btn btn-info" name="submit" value="Add">
	    					            </div>
	    					        </div>
    					        </div>
    					    </form>
    					</div>
    				</div>
    			</div>
    		</div>
    	</section>
	</section>

@endsection

resources/views/posts/postDetail.blade.php
@extends('../layout.master')
@section('title', 'Post Detail')
@section('content')

	<section class="main_section">
		@if(session()->has('message'))
		    <div class="alert alert-success">
		        {{ session()->get('message') }}
		    </div>
		@endif 
    	<div class="col-xl-12">
    		<div class="top_bar">
				<div class="left">
				</div>
				<div class="right">
					<a href="{{ route('posts.index') }}" class="btn btn-success">Back</a>
				</div>
    		</div>
			<div class="table-responsive">
				<table class="table table-hover">
					<thead>
						<tr>
							<th>Id</th>
							<th>Name</th>
							<th>Description</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>{{ $post->id }}</td>
							<td>{{ $post->post_name }}</td>
							<td>{{ $post->short_description }}</td>
							<td>{{ $post->description }}</td>
						</tr>
					</tbody>
				</table> 
			</div>
    	</div>
	</section>

@endsection

resources/views/posts/postImage.blade.php
@extends('../layout.master')
@section('title', 'Post image')
@section('content')
    <section class="main_section">
        <div class="col-xl-12">
            <div class="top_bar">
                <div class="left">
                    <h2 class="text-info">
                        Add Image 
                    </h2>
                </div>
                <div class="right">
                    <a href="{{ route('posts.index') }}" class="btn btn-success">Back</a>
                </div>
            </div>
        </div>
        <section class="form_section">
            <!--Form Section Start-->
            <div class="form_area">
                <div class="row">
                    <div class="col-md-12">
                        <form class="row form" action="{{ route('posts.image.save', ['id' => $post->id])}}" method="POST" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="name">Image Upload</label>
                                    <input class="form-control" type="file" name="image">
                                    @error('image')
                                        <div class="text-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="email">Status</label>
                                    <select name="status" class="form-control">
                                        <option value="">Select Status</option>
                                        <option value="1">Enable</option>
                                        <option value="0">Disable</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group" style="margin-top:30px;">
                                    <input type="submit" class="btn btn-primary" value="Submit">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!--Form Section End-->


            <!--VIew Section Start-->
            <div class="view_area">
                <table class="table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Image</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>
                                <a href="" class="btn btn-danger">
                                    <i class="fa fa-trash"></i>
                                </a>
                                <a href="" class="btn btn-info">
                                    <i class="fa fa-pencil"></i>
                                </a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <!--VIew Section End-->
        </section>
    </section>
@endsection

resources/views/posts/postImage1.blade.php
@extends('../layout.master')
@section('title', 'Post image')
@section('content')
    <section class="main_section">
        <div class="col-xl-12">
            <div class="top_bar">
                <div class="left">
                    <h2 class="text-info">
                        Add Image 
                    </h2>
                </div>
                <div class="right">
                    <a href="{{ route('posts.index') }}" class="btn btn-success">Back</a>
                </div>
            </div>
        </div>
        <section class="form_section">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="form_area">
                            <!--<div class="row">
                                <div class="col-xl-6">
                                    <div class="form-group">
                                        <label>Post Title:</label>
                                        <input type="text" class="form-control" name="name" value="{{ $post->post_name }}">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xl-6">
                                    <div class="form-group">
                                        <label>Short Description:</label>
                                        <input type="text" class="form-control" name="short_description" value="{{ $post->short_description }}">
                                        @error('short_description')
                                            <div class="text-danger">{{ $message }}</div>
                                        @enderror
                                    </div>
                                </div>
                            </div>-->
                            <div class="row">
                                <div class="col-xl-6">
                                    <label>Image:</label>
                                    <form method="post" action="{{ route('posts.image.save', ['id' => $post->id]) }}" enctype="multipart/form-data"
                                          class="dropzone" id="dropzone">
                                        @csrf
                                    </form>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xl-6">
                                    <div class="form-group">
                                        <a class="btn btn-info" href="" onclick="event.preventDefault(); document.getElementById('dropzone').submit();">Add Image</a> 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </section>
@endsection

resources/views/posts/postList.blade.php
@extends('../layout.master')
@section('title', 'Post Listing')
@section('content')

	<section class="main_section">
		@if(session()->has('message'))
		    <div class="alert alert-success">
		        {{ session()->get('message') }}
		    </div>
		@endif 
    	<div class="col-xl-12">
    		<div class="top_bar">
				<div class="left">
				</div>
				<div class="right">
					<a href="{{ route('posts.create') }}" class="btn btn-info">Create Post</a>
					<a href="{{ route('posts.index') }}" class="btn btn-success">Back</a>
				</div>
    		</div>
			<div class="table-responsive">
				<table class="table table-hover">
					<thead>
						<tr>
							<th>Id</th>
							<th>Name</th>
							<th>Description</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($posts as $post)
							<tr>
								<td>{{ $post->id }}</td>
								<td>{{ $post->post_name }}</td>
								<td>{{ Illuminate\Support\Str::limit($post->short_description, 50) }}</td>
								<td>
									<a href="{{ route('posts.edit', ['id' => $post->id]) }}" class="btn btn-info">
										<i class="fa fa-pencil"></i>
									</a>
									<!--<a href="{{ route('posts.view', ['id' => $post->id]) }}" class="btn btn-primary">
										<i class="fa fa-eye"></i>
									</a>-->
									<form method="POST" action="{{ route('posts.delete', ['id' => $post->id]) }}" style="margin-right: 5px; margin-top:5px;">
									    {{ csrf_field() }}
									    {{ method_field('DELETE') }}
									    <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
									</form>
									<a href="{{ route('posts.image', ['id' => $post->id]) }}"class="btn btn-info">
										Add Image
									</a>
								</td>
							</tr>
						@endforeach
					</tbody>
				</table> 
			</div>
    	</div>
	</section>
@endsection